# Generated by Django 4.2 on 2023-04-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_account_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='registered_dttm',
        ),
    ]
