# Generated by Django 4.2 on 2023-04-30 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_remove_account_registered_dttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
    ]
